contact/urls.py
from contact import views
from django.urls import path

app_name = 'contact'

urlpatterns = [
    #Inicial Index
    path('', views.index, name='index'),

    #Paginal Entregas
    path('entregas/', views.entregas, name='entregas'),
    path('search_entrega/', views.search_entrega, name='search_entrega'),
    
    #Pagina Ocorrencias
    path('ocorrencia/', views.ocorrencia, name='ocorrencia'),
    path('search_ocorrencia/', views.search_ocorrencia, name='search_ocorrencias'),
    
    #CRUD Entregas
    path('entregas/<int:entrega_id>/detail/', views.entregas_id, name='entregas_id'),
    path('entregas/create/', views.create_entregas, name='create_entregas'),
    path('entregas/<int:entrega_id>/update/', views.update_entregas, name='update_entregas'),
    path('entregas/<int:entrega_id>/delete/', views.delete_entrega, name='delete_entrega'),
    
    
    #CRUD Ocorrencias
    path('ocorrencia/<int:ocorrencia_id>/detail/', views.ocorrencia_id, name='ocorrencias_id'),
    path('ocorrencia/create/', views.create_ocorrencia, name='create_ocorrencia'),
    path('ocorrencia/<int:ocorrencia_id>/update/', views.update_ocorrencia, name='update_ocorrencia'),
    path('ocorrencia/<int:ocorrencia_id>/delete/', views.delete_ocorrencia, name='delete_ocorrencia'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
 
# Create your models here.
class Entrega(models.Model):
    apt = models.CharField(max_length=10)
    nome = models.CharField(max_length=100)
    fotos = models.ImageField(blank=True, upload_to='entregas/%Y/%m/')
    data = models.DateTimeField(default=timezone.now)
    receberam = models.BooleanField( blank=True)

    def __str__(self) -> str:
        return self.nome

class Ocorrencia(models.Model):
    data = models.DateTimeField(default=timezone.now)
    ocorrencia = models.TextField(blank=True)
    nomeResp = models.CharField(max_length=200, blank=True)

    def __str__(self) -> str:
        return self.nomeResp

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models

# Class do Formulario da Entregas
class EntregasForm(forms.ModelForm):
    fotos = forms.ImageField(
       widget=forms.FileInput(
           attrs={
               'accept': 'image/*',
               }
        )
    )
    # Este é uns dos campos do formulario, o jeito que voce que no formulario...
    apt = forms.CharField( 
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Numero apt',
                }
            ),label='Numero do apartamento')
    
    # Este é uns dos campos do formulario, o jeito que voce que no formulario...
    nome = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder' : 'Destinario'}))
    

    # Meta é oque voce vai bota no formulario...
    class Meta :
        model = models.Entrega
        fields = (
            'apt', 'nome', 'receberam', 'fotos',
        )

    # essa Função é para verificar ser tem algum erro no formulario.
    def clean(self):
        # Validando ser tem algum error no campo 'apt'
        apt = self.cleaned_data.get('apt')
        if apt == '2500':
            self.add_error(
                'apt',
                ValidationError(
                    'Nao pode ser acima de 2400', code='invalid'
                )
            )
            return super().clean()
        
        # Este é a validaçao do 'nome'
        nome = self.cleaned_data.get('nome')
        if nome == 'abc':
            self.add_error(
                'nome', ValidationError(
                    'Não pode colocar abc', code='invalid'
                )
            )
            return super().clean()
        
# Class do Formulario da Ocorrencia
class OcorrenciaForm(forms.ModelForm):
    # adcionando o jeito que deseja coloca no campo 'nomeResp'
    nomeResp = forms.CharField(
        widget= forms.TimeInput(
            attrs= {
                'placeholder': 'Ronda/Porteiro seu Nome',
            }
        ), label='Nome'
    )
    # adcionando o jeito que deseja coloca no campo 'ocorrencia'
    ocorrencia = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Digite seu Livro de Ocorrencia aqui...',
            }
        )
    )

    # Meta é oque voce vai bota no formulario...
    class Meta:
        model = models.Ocorrencia
        fields = (
            'nomeResp', 'ocorrencia',
        )
    # essa Função é para verificar ser tem algum erro no formulario.
    def clean(self):
        # Este é a validaçao do 'nomeResp'
        nomeResp = self.cleaned_data.get('nomeResp')
        if nomeResp == 'abc':
            self.add_error(
                'nomeResp', ValidationError(
                    'Coloque seu Nome', code='invalid'
                )
            )
        return super().clean()

contact/views.py
from django.shortcuts import render, get_object_or_404, redirect
from contact.models import *
from django.db.models import Q
from django.core.paginator import Paginator
from django import forms
from django.urls import reverse
from contact.forms import *

# Create your views here.
def index(request):

    return render (
        request,
        "global/base.html",
    )

def entregas(request):

    entregas = Entrega.objects.filter().order_by('-id')

    paginator = Paginator(entregas , 10)
    page_number = request.GET.get("page")
    entrega_page_obj = paginator.get_page(page_number)
    
    context = {
        'entrega_page_obj' : entrega_page_obj,
        'site_title' : 'Registros de Entregas -',
    }
    
    return render (
        request,
        'contact/index.html',
        context,
    )

def ocorrencia(request):

    ocorrencias = Ocorrencia.objects.filter().order_by('-id')

    paginator = Paginator(ocorrencias , 10)
    page_number = request.GET.get("page")
    ocorrencia_page_obj = paginator.get_page(page_number)

    context = {
        'ocorrencia_page_obj': ocorrencia_page_obj,
        'site_title' : 'Registros de Ocorrencias -',
    }

    return render (
        request,
        'contact/ocorencias.html',
        context,
    )

def entregas_id(request, entrega_id):

    # singles_entrega = Entrega.objects.filter(pk=entrega_id).first()
    singles_entrega = get_object_or_404(Entrega,pk=entrega_id )
    
    entregas = f'{singles_entrega.nome} '

    context = {
        'entrega' : singles_entrega,
        'site_title' : entregas,
    }
    
    return render (
        request,
        'contact/entrega_id.html',
        context,
    )

def ocorrencia_id(request, ocorrencia_id):

    singles_ocorrencias = get_object_or_404(Ocorrencia,pk=ocorrencia_id )
    
    context = {
        'ocorrencia' : singles_ocorrencias,
    }
    
    return render (
        request,
        'contact/ocorrencia_id.html',
        context,
    )

def search_entrega(request):
    search_entrega = request.GET.get('q', '').strip()

    if search_entrega == '':
        return redirect('contact:entregas')

    entregas = Entrega.objects\
        .filter()\
        .filter(
            Q(receberam__icontains=search_entrega)|
            Q( data__icontains=search_entrega) | 
            Q( apt__icontains=search_entrega) 
            )\
        .order_by('-id')
    
    paginator = Paginator(entregas , 10)
    page_number = request.GET.get("page")
    entrega_page_obj = paginator.get_page(page_number)
    
    context = {
        'entrega_page_obj' : entrega_page_obj,
        'site_title' : 'Search_entregas -',
        'search_entrega':search_entrega,
    }
    
    return render (
        request,
        'contact/index.html',
        context,
    )

def search_ocorrencia(request):
    search_ocorrencias = request.GET.get('q', '').strip()

    if search_ocorrencias == '':
        return redirect('contact:search_ocorrencias')

    ocorrencias = Ocorrencia.objects\
        .filter()\
        .filter(
            Q(data__icontains=search_ocorrencias)|
            Q(nomeResp__icontains=search_ocorrencias)
            )\
        .order_by('-id')
    
    paginator = Paginator(ocorrencias , 10)
    page_number = request.GET.get("page")
    ocorrencia_page_obj = paginator.get_page(page_number)

    
    context = {
        'ocorrencia_page_obj' : ocorrencia_page_obj,
        'site_title' : 'Search_ocorrencias -',
        'search_ocorrencias':search_ocorrencias,
    }
    
    return render (
        request,
        'contact/ocorencias.html',
        context,
    )

 
def create_entregas(request):
    form_action = reverse('contact:create_entregas')

    if request.method == 'POST':
        form_entrega = EntregasForm(request.POST, request.FILES)
        context = {
            'form': form_entrega,
            'form_action' : form_action,
        }
        if form_entrega.is_valid():
            form_entrega.save()
            return redirect('contact:entregas')

        return render (
            request,
            'contact/create_entrega.html',
            context,
        )
    
    context = {
        'form':EntregasForm(),
        'form_action' : form_action,
    }
    return render (
        request,
        'contact/create_entrega.html',
        context,
    )

def update_entregas(request, entrega_id):
    entregas = get_object_or_404(Entrega, pk=entrega_id,)

    form_action = reverse('contact:update_entregas', args=(entrega_id,))

    if request.method == 'POST':
        form_entrega = EntregasForm(request.POST, request.FILES, instance=entregas)
        context = {
            'form': form_entrega,
            'form_action' : form_action,
        }
        if form_entrega.is_valid():
            entregas = form_entrega.save()
            return redirect('contact:entregas_id', entrega_id=entregas.pk)

        return render (
            request,
            'contact/create_entrega.html',
            context,
        )
    
    context = {
        'form':EntregasForm(instance=entregas),
        'form_action' : form_action,
    }
    return render (
        request,
        'contact/create_entrega.html',
        context,
    )

def create_ocorrencia(request):
    form_action = reverse('contact:create_ocorrencia')
    if request.method == 'POST':
        form_ocorrencia = OcorrenciaForm(request.POST)
        context = {
            'forms': form_ocorrencia,
            'form_action' : form_action,
        }

        if form_ocorrencia.is_valid():
            form_ocorrencia.save()
            return redirect('contact:ocorrencia')

        return render (
            request,
            'contact/create_ocorrencia.html',
            context,
        )

    context = {
        'forms':OcorrenciaForm(),
        'form_action' : form_action,
    }
    return render (
        request,
        'contact/create_ocorrencia.html',
        context,
    )

def update_ocorrencia(request, ocorrencia_id):
    ocorrencia = get_object_or_404(Ocorrencia, pk=ocorrencia_id)

    form_action = reverse('contact:update_ocorrencia', args=(ocorrencia_id,))

    if request.method == 'POST':
        form_ocorrencia = OcorrenciaForm(request.POST, instance=ocorrencia)
        context = {
            'forms': form_ocorrencia,
            'form_action' : form_action,
        }

        if form_ocorrencia.is_valid():
            ocorrencia= form_ocorrencia.save()
            return redirect('contact:ocorrencias_id', ocorrencia_id=ocorrencia.pk)

        return render (
            request,
            'contact/create_ocorrencia.html',
            context,
        )

    context = {
        'forms':OcorrenciaForm(instance=ocorrencia),
        'form_action' : form_action,
    }
    return render (
        request,
        'contact/create_ocorrencia.html',
        context,
    )


def delete_entrega(request, entrega_id):
    entregas = get_object_or_404(Entrega, pk=entrega_id,)
    entregas.delete()
    return redirect('contact:entregas')

def delete_ocorrencia(request, ocorrencia_id):
    ocorrencia = get_object_or_404(Ocorrencia, pk=ocorrencia_id)
    ocorrencia.delete()
    return redirect('contact:ocorrencia')

contact/templates/contact/create_entrega.html
{% extends "global/base.html" %}

{% block contente %}

<div class="form-wrapper">

    <h2>Cria Entregas</h2>

    <form action="{{ form_entrega }}" 
        method="POST" 
        enctype="multipart/form-data">

        {% csrf_token %}
        
        {% for field in form %}
        <div class="form-content">


            <div class="form-group">

                <label for="{{ field.id_for_label }}"> {{ field.label }} </label>
                {{ field }}
                
                {{ field.errors }}
                
            </div>
            {% if field.name == 'fotos' and field.value.url %} 
            <div class="form-group">
                <img src="{{ field.value.url  }}" alt="img" style="max-width: 200px;">
            </div>
            {% endif %}

            
        </div>
        {% endfor %}
        
        <div class="form-content">
            <div class="form-group">
                <button class="btn" type="submit">Enviar</button>
            </div>
        </div>



    </form>
</div>
{% endblock contente %}

contact/templates/contact/create_ocorrencia.html
{% extends "global/base.html" %}

{% block contente %}

<div class="form-wrapper">

    <h2>Cria Ocorrencias</h2>

    <form action="{{ form_entrega }}"
     method="POST" 
     enctype="multipart/form-data"
     >

        {% csrf_token %}

        {% for field in forms %}
        <div class="form-content">


            <div class="form-group">

                <label for="{{ field.id_for_label }}"> {{ field.label }} </label>
                {{ field }}
                {{ field.errors }}

            </div>


        </div>
        {% endfor %}

        <div class="form-content">
            <div class="form-group">
                <button class="btn" type="submit">Enviar</button>
            </div>
        </div>

    </form>
</div>
{% endblock contente %}

contact/templates/contact/entrega_id.html
{% extends "global/base.html" %}
{% block contente %}
<div>
    <div class='single-perfil'>
        {% comment %} <h1>id:  {{ entrega.id }}  </h1>  {% endcomment %}
        <p><b>Nome:</b> {{ entrega.nome }}</p>
        <p><b>data:</b> {{ entrega.data }}</p>
        <p><b>apt:</b> {{ entrega.apt }}</p>
        <p><b>receberam:</b> {{ entrega.receberam }}</p>

        {% if entrega.fotos %}
        <p>
            <img src=" {{ entrega.fotos.url }} " alt=" {{ entrega.nome }} ">
        </p>
        {% endif %}
    </div>

    <div class="form-buttons">
        <a href="{% url 'contact:update_entregas' entrega.id %}" class="btn atualizar">
          Atualizar
        </a>
      
        <form action='{% url "contact:delete_entrega" entrega.id %}'  method="POST" class="form-inline">
          {% csrf_token %}
          <button type="submit" class="btn apagar">Apagar</button>
        </form>
      </div>
</div>
{% endblock contente %}

contact/templates/contact/index.html
{% extends "global/base.html" %}
{% block contente %}
<div>
    <div>
        <a class="btn-adc" href=" {% url 'contact:create_entregas' %} ">Adicionar</a>
    </div>
    <section class="main-sect">

        <div class="table-caption">
            <form action="{% url 'contact:search_entrega' %}" method='get' >
                <input type="search" 
                placeholder="Buscar entrega"
                id="search"
                name = "q"
                value='{{ request.GET.q.strip }}'
                required>
            </form>
        </div>

        {% if entrega_page_obj %}
        
        <div class="responsive-table">
            <table class="table-menu">
                
                <thead class="table-thead">
                    
                    <tr class="table-tr">
                        
                        <th class="table-th">Dia</th>
                        <th class="table-th">Apt</th>
                        <th class="table-th">
                            <div class="we">
                                Receberam
                            </div>
                        </th>
                        
                    </tr>
                    
                </thead>
                
                <tbody class="table-tbody">
                    {% for entrega in entrega_page_obj %}
                    <tr>
                        <td class="table-td">
                            <a class="link-a" href="{% url 'contact:entregas_id' entrega.id %} ">
                                {{ entrega.data }}
                            </a>
                        </td>
                        
                        <td class="table-td">
                            {{ entrega.apt }}
                        </td>
                        
                        
                        <td class="table-td">
                            {{ entrega.receberam }}
                        </td>
                    </tr>
                    
                    {% endfor %}
                </tbody>
            </table>

            {% include "contact/pag_entrega.html" %}

        </div>
        {% else %}
        <div class='single-perfil'>
            Nada encontrado...
        </div>

        {% endif %}




    </section>
</div>
{% endblock contente %}

contact/templates/contact/ocorencias.html
{% extends "global/base.html" %}
{% block contente %}

<div>
    <div>
        <a class="btn-adc" href=" {% url 'contact:create_ocorrencia' %} ">Adicionar</a>
    </div>
    <section class="main-sect">

        <div class="table-caption">
            <form action="{% url 'contact:search_ocorrencias' %}" method='get' >
                <input type="search" 
                placeholder="Buscar ocorrencia"
                id="Buscar"
                name = "q"
                value='{{ request.GET.q.strip }}'
                required>
            </form>
        </div>

        {% if ocorrencia_page_obj %}

        <div class="responsive-table">
            <table class="table-menu">

                <thead class="table-thead">

                    <tr class="table-tr">

                        <th class="table-th">Dia</th>
                        <th class="table-th">nome_Resp</th>
                        
                    </tr>

                </thead>

                <tbody class="table-tbody">
                    {% for ocorrencia in ocorrencia_page_obj %}
                    <tr>
                        <td class="table-td">
                            <a class="link-a" 
                            href=" {% url 'contact:ocorrencias_id' ocorrencia.id %} "
                            >
                                {{ ocorrencia.data }}
                            </a>
                        </td>

                        <td class="table-td">
                            {{ ocorrencia.nomeResp }}
                        </td>

                    </tr>

                    {% endfor %}
                </tbody>
            </table>

            {% include "contact/pag_ocorrencia.html" %}

        </div>

        {% else %}
        <div class='single-perfil'>
            Nada encontrado...
        </div>

        {% endif %}

    </section>
</div>
{% endblock contente %}

contact/templates/contact/ocorrencia_id.html
{% extends "global/base.html" %}
{% block contente %}
<div>
    <div class='single-perfil'>
        {{ ocorrencia.nomeResp }} 
        <p><b>Data:</b> {{ ocorrencia.data }}</p>
        <p><b>Ocorrencias:</b> {{ ocorrencia.ocorrencia }}</p>
    </div>
    <div class="form-buttons">
        <a href="{% url 'contact:update_ocorrencia' ocorrencia.id %}" class="btn atualizar">
          Atualizar
        </a>
      
        <form action="{% url 'contact:delete_ocorrencia' ocorrencia.id %}" method="POST" class="form-inline">
          {% csrf_token %}
          <button type="submit" class="btn apagar">Apagar</button>
        </form>
      </div>
</div>
{% endblock contente %}

contact/templates/contact/pag_entrega.html
{% if entrega_page_obj %}

<div class="pagination">
    <span class="step-links">
        {% if entrega_page_obj.has_previous %}
        <a href="?page=1&q={{ request.GET.q.strip }}">&laquo; Inicio</a>
        <a href="?page={{ entrega_page_obj.previous_page_number }}&q={{ request.GET.q.strip }}">Volta</a>
        {% endif %}
        
        <span class="current">
            Pag {{ entrega_page_obj.number }} de {{ entrega_page_obj.paginator.num_pages }}.
        </span>
        
        {% if entrega_page_obj.has_next %}
        <a href="?page={{ entrega_page_obj.next_page_number }}&q={{ request.GET.q.strip }}">Proxima</a>
        <a href="?page={{ entrega_page_obj.paginator.num_pages }}&q={{ request.GET.q.strip }}">final &raquo;</a>
        {% endif %}
    </span>
</div>

{% endif %}

contact/templates/contact/pag_ocorrencia.html
{% if ocorrencia_page_obj %}

<div class="pagination">
    <span class="step-links">
        {% if ocorrencia_page_obj.has_previous %}
        <a href="?page=1&q={{ request.GET.q.strip }}">&laquo; Inicio</a>
        <a href="?page={{ ocorrencia_page_obj.previous_page_number }}&q={{ request.GET.q.strip }}">Volta</a>
        {% endif %}
        
        <span class="current">
            Pag {{ ocorrencia_page_obj.number }} de {{ ocorrencia_page_obj.paginator.num_pages }}.
        </span>
        
        {% if ocorrencia_page_obj.has_next %}
        <a href="?page={{ ocorrencia_page_obj.next_page_number }}&q={{ request.GET.q.strip }}">Proxima</a>
        <a href="?page={{ ocorrencia_page_obj.paginator.num_pages }}&q={{ request.GET.q.strip }}">final &raquo;</a>
        {% endif %}
    </span>
</div>

{% endif %}